spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 

mybatis:
  mapper-locations:
  - classpath*:io/github/fpure/admin/**/*Mapper.xml